### ISSUE TITLE
스크립트 만들기!!

### ISSUE THREAD

**Issue by ghost** [openstack-kr/ubuntu-script-community-ver#1]
언제 해보나 너무 바쁨 ㅠㅠ

**Comment by tzniuta** [comment]
45454

**Comment by ghost** [comment]
빨리하자!!! 

![openstack-logical-arch-folsom](https://cloud.githubusercontent.com/assets/7867447/7550916/d7bd15be-f6af-11e4-9f1a-678c1062114f.jpg)

**Comment by ghost** [comment]
다했다!!!

**Comment by ghost** [comment]
다시 열어라!!
